### ISSUE TITLE
お気に入り出発地のから情報を反映する

### ISSUE THREAD

**Issue by kerochelo** [SatoshiUmeda1803/haya_map#29]
## 概要
お気に入り出発地のから情報を反映する処理を作る

### 内容
1. お気に入りの出発地をクリックする
2. クリックした出発地の住所情報を出発地のフォームに入れる

ブラウザで処理を作る(JSを利用する)
例：東京駅

お気に入りの東京駅をクリック
東京駅の住所を取得する
取得した住所情報をフォームに入れる

**Comment by kerochelo** [comment]
```html
  <body>
    <form>
      <input id="t" name="a" value="">
      <input id="3" type="button" value="お気に入りの出発地" onclick="buttonClick()">
    </form>
    <script>
    function buttonClick(e){
      var e = e || window.event;
      var elem = e.target || e.srcElement;
      var elemId = elem.id;
      document.getElementById("t").value=elemId;
    }
    </script>
  </body>
```

**Comment by SatoshiUmeda1803** [comment]
@kerochelo 
できました！！！！
上記のコードのボタンを、パーシャルに持っていって、お気に入り出発地一覧の横に表示しようとしたときに、ボタンのidを住所にしたらいいんじゃない？ということで
```
<div class="containner">
  <%= fav_start.name %>
  <%= button_tag 'この出発地を使う', id: fav_start.address, type: 'button' , onclick: 'buttonClick()' %>
</div>
```
にしたらできました！！！
![スクリーンショット 2022-09-01 16 11 27](https://user-images.githubusercontent.com/99541405/187853926-fe723768-71ae-4122-9270-0eb46e3e8a0b.png)

教えていただいたことをいろいろ飛ばしちゃってる気がするのと、idを住所にしちゃうのはどうなのかというところはあるので改善の余地はありそうですが、とりあえず機能は実装できました！！！！
ありがとうございました！！！！！！！
